import { section as s } from "./domains.mjs";
const nf = ["cambridge-nonfinite-scope", "cambridge-comprehensive-scope"];
export const sections = [
  s(
    "noun-clauses",
    "content-clauses",
    "content-clause-functions",
    "Content clauses as subjects, complements and explanations",
    "A content clause expresses a proposition or question and can fill several grammatical roles. It can follow a verb, noun or adjective, or function as a subject. A that-clause after a noun supplies content, while a relative clause usually identifies or describes the noun through a gap.",
    "the claim **that she resigned**",
    [
      "**That he apologised** matters.",
      "We are certain **that the figures are correct**.",
    ],
    "The claim that she made has a relative gap after made; the claim that she resigned gives the content of the claim. Similar openings can hide different structures.",
  ),
  s(
    "noun-clauses",
    "content-clauses",
    "embedded-if-whether",
    "Whether, if and embedded alternatives",
    "Whether and if can introduce embedded yes/no questions after many verbs. Whether is generally required before a to-infinitive and preferred or required in some fronted clauses, after prepositions and with explicit alternatives. Embedded questions use statement order; subject questions already have their question word as subject.",
    "I wonder **whether she agrees**.",
    [
      "We discussed **whether to postpone** it.",
      "It depends **on whether they agree**.",
    ],
    "If also introduces conditions. I’ll ask if she comes can be ambiguous between asking whether she comes and asking only on the condition that she comes.",
  ),
  s(
    "noun-clauses",
    "content-clauses",
    "extraposition-object-it",
    "Anticipatory subjects and objects with it",
    "English often puts a long subject clause later and uses it in the initial subject position. Certain verbs also allow anticipatory object it before an adjective or noun complement. This arrangement keeps a heavy clause near the end and gives the reader an easier starting point. Only verbs licensing the pattern allow it.",
    "**It** is clear **that she agrees**.",
    [
      "I find **it difficult to concentrate**.",
      "We made **it clear that we would not pay**.",
    ],
    "Do not insert it before every clause object: I know that she agrees is ordinary; I know it that she agrees is not the same standard pattern.",
  ),
  s(
    "reported-statements",
    "content-clauses",
    "reporting-reference-backshift",
    "Backshift, pronouns and reporting perspective",
    "Reporting changes the viewpoint from the original speaker to the reporter. Past reporting verbs often invite backshift, but a statement still treated as true can keep its original tense. Pronouns and time expressions change only if the referents or reference time change. Direct quotation preserves the original wording; indirect reporting conveys the message.",
    "“I am ready.” → She said **she was ready**.",
    [
      "She said **she lives nearby**, and she still does.",
      "On Tuesday he said, “I’ll leave tomorrow.” Later: he said he would leave **on Wednesday**.",
    ],
    "Backshift is not an instruction to replace every present with past regardless of meaning. The reporter’s commitment and time frame matter.",
  ),
  s(
    "relative-clauses",
    "relatives",
    "relative-gap-functions",
    "Relative pronouns as subjects, objects and complements",
    "A relative construction connects a noun or other antecedent to a missing role inside a clause. The relative expression may supply the subject, object, possessive determiner or complement of a preposition. Locate the missing role before choosing who, whom, which, whose, that or omission. A noun’s meaning alone is insufficient.",
    "the city **which we visited** / the city **where we stayed**",
    [
      "The person **whom we invited** declined.",
      "The tool **with which she worked** was old.",
    ],
    "Do not repeat the object when the relative already represents it: the book that I read, not the book that I read it in the ordinary standard construction.",
  ),
  s(
    "relative-clauses",
    "relatives",
    "whole-clause-relative",
    "Relative clauses referring to a whole situation",
    "A supplementary which-clause can comment on an entire preceding proposition rather than on one noun. Commas signal that it is additional information. The interpretation comes from the meaning of the comment and the preceding clause. Keep the antecedent clear when the clause contains several possible nouns and events.",
    "She missed the train, **which delayed the trip**.",
    [
      "He apologised, **which surprised everyone**.",
      "The road was closed, **which meant a long detour**.",
    ],
    "That does not normally introduce this supplementary whole-clause relative. If which could refer to a noun or event ambiguously, split the message into two sentences.",
  ),
  s(
    "relative-clauses",
    "relatives",
    "fused-free-relatives",
    "What, whoever and fused relative constructions",
    "A fused or free relative combines the role of a noun-like expression with a relative clause, without a separate head noun. What can mean the thing that; whoever can mean any person who. These expressions can function as subjects or objects. Some -ever clauses instead express a concessive condition.",
    "Keep **what you need**.",
    [
      "**Whoever arrives first** can choose a seat.",
      "I liked **what she suggested**.",
    ],
    "Do not add a separate antecedent before relative what in ordinary standard English: the thing that I need or what I need, not the thing what I need.",
  ),
  s(
    "relative-clauses",
    "relatives",
    "relative-quantifiers-and-whereby",
    "Quantified relatives, whose for things and whereby",
    "A supplementary relative can contain a quantifier plus of whom or of which. Whose can refer to things as well as people when it marks a possessive relationship. Whereby is a formal relative connector meaning by which means. These patterns let a writer attach a precise relationship to an identified set or process.",
    "ten applicants, **three of whom** were selected",
    [
      "We visited a village **whose roads were flooded**.",
      "They introduced a system **whereby members could vote online**.",
    ],
    "Keep the quantifier’s agreement clear: one of whom was selected but three of whom were selected. Do not substitute who for of whom after this quantifier pattern.",
  ),
  s(
    "relative-clauses",
    "relatives",
    "long-distance-dependencies",
    "Long-distance questions and relative links",
    "A question or relative expression can correspond to a role inside an embedded clause: the person who I think called. The grammatical form depends on that embedded role. Such dependencies have limits; not every expression can be moved out of every clause or noun phrase. Reword a construction when a distant link becomes hard to follow.",
    "Who do you think **___ called**? (The gap marks the subject’s position.)",
    [
      "This is the book **that I said I needed**.",
      "Who do you believe **will win**?",
    ],
    "In Who do you think called?, who is the embedded subject. Its distance from called does not turn it into an object requiring whom.",
  ),
  s(
    "participle-clauses",
    "nonfinite",
    "nonfinite-forms-functions",
    "Infinitival, -ing and past-participial clauses",
    "Non-finite clauses use a to-infinitive, a bare infinitive, an -ing form or a past participle. They may act as complements, modifiers or adjuncts. They have no independent tense but can express earlier time through perfect constructions. Active/passive distinctions remain possible. A traditional gerund is an -ing form in a noun-like clause role.",
    "**to have left** · **being repaired** · **having been told**",
    [
      "**Swimming regularly** helps me relax.",
      "The window **broken in the storm** was replaced.",
    ],
    "An -ing clause can take an object and adverb: carefully reading the letter. A deverbal noun behaves differently: the careful reading of the letter.",
    nf,
  ),
  s(
    "verb-patterns",
    "nonfinite",
    "control-understood-subjects",
    "Who does the action in an infinitive?",
    "An infinitive often has an understood subject supplied by the main clause. Different verbs assign that role differently. With promise to do something, the promiser normally does it; with persuade someone to do something, the person persuaded does it. Some constructions instead express a general or contextually supplied actor.",
    "She **promised to leave** / She **persuaded him to leave**",
    [
      "Maya **promised to help**: Maya would help.",
      "Maya **persuaded Leo to help**: Leo would help.",
    ],
    "The noun nearest the infinitive is not always its understood subject. Read the main verb’s construction and meaning rather than applying a proximity shortcut.",
    nf,
  ),
  s(
    "verb-patterns",
    "nonfinite",
    "raising-seem-appear",
    "Seem, appear and raising constructions",
    "In she seems to know, the main subject belongs semantically with the infinitive: she knows. The sentence can often be paraphrased with it seems that. This differs from a verb such as promise, whose subject also participates in the main event. Passive and perfect infinitives can occur after seem and appear.",
    "She **seems to know** / It **seems that she knows**.",
    ["There **seems to be** a mistake.", "He **appears to have left**."],
    "There seems to be is possible because seems need not assign an action role to its subject. There promises to leave does not have the same ordinary structure.",
    nf,
  ),
  s(
    "verb-patterns",
    "nonfinite",
    "bare-infinitives-perception-causation",
    "Bare infinitives after modals, let, make and perception verbs",
    "Central modals take a bare infinitive. Let and causative make normally do too; help allows forms with or without to. Perception verbs can take an object plus bare infinitive for an event viewed as a whole, or an -ing clause for an event viewed in progress. Passive make commonly restores to.",
    "They **made him wait**. / He **was made to wait**.",
    ["I saw her **cross** the road.", "I saw her **crossing** the road."],
    "The perception contrast is about how the event is presented, not a guarantee of actual completion in every imaginable context. Causative let is normally replaced by be allowed to in a passive.",
    nf,
  ),
  s(
    "infinitive-of-purpose",
    "nonfinite",
    "for-subject-and-tough",
    "For + subject, infinitival relatives and tough constructions",
    "For can introduce an explicit subject of a to-infinitive. An infinitive can also modify a noun or follow an adjective with an understood object linked to the main subject. In This book is easy to read, the book is what someone reads. These links explain why a repeated object pronoun is usually unnecessary.",
    "a place **to stay** / **for us to stay**",
    [
      "It is important **for everyone to know**.",
      "The problem is **hard to solve**.",
    ],
    "For her to leave expresses the infinitive’s subject; to her is not interchangeable. This problem is hard to solve it repeats an object already understood from the main subject.",
    nf,
  ),
  s(
    "participle-clauses",
    "nonfinite",
    "absolute-and-verbless-clauses",
    "Absolute constructions and clauses without a verb",
    "Some supplementary non-finite clauses have their own subject, as in the weather permitting. Others omit a recoverable form of be and are called verbless clauses. They can express time, condition, concession or circumstances. These compact patterns are common in formal descriptions and instructions, but clarity of attachment remains essential.",
    "**Weather permitting**, we will leave.",
    [
      "**Although tired**, she continued.",
      "He stood there, **his hands in his pockets**.",
    ],
    "A separate subject in an absolute construction is possible; the shared-subject rule for ordinary participial adjuncts does not apply mechanically to every non-finite supplement.",
    nf,
  ),
  s(
    "participle-clauses",
    "nonfinite",
    "dangling-and-perfect-participles",
    "Participial attachment, anteriority and passive meaning",
    "An ordinary supplementary participial clause usually takes its understood subject from the main clause. A perfect participle presents its event as earlier than the main event; a passive participle presents the understood subject as affected. If the intended actor differs, supply it explicitly or rewrite the clause.",
    "**Having checked** the route, we left.",
    [
      "**Warned about the ice**, the driver slowed down.",
      "**After I read the report**, the error became clear.",
    ],
    "Reading the report, the error became clear misleadingly makes the error the reader. Conventional speaker-oriented expressions such as generally speaking are established exceptions.",
    nf,
  ),
  s(
    "verb-pattern-meaning",
    "nonfinite",
    "remember-forget-regret",
    "Remember, forget and regret: time and meaning",
    "Remember or forget + to-infinitive concerns a duty or intended action. Remember + -ing recalls an experience; never forget + -ing highlights a memorable one. Regret + -ing looks back with regret, while regret to say/inform conventionally introduces bad news. The complement changes the relation between the mental event and the other action.",
    "remember **to call** / remember **calling**",
    [
      "I forgot **to lock** the door.",
      "I regret **telling** him, but I regret **to inform** you that it is too late.",
    ],
    "Remembering to do something normally implies that the action is carried out in the relevant narrative; merely thinking about an intended future duty may need different wording.",
    nf,
  ),
  s(
    "verb-pattern-meaning",
    "nonfinite",
    "try-go-on-mean",
    "Try, go on, mean and need with different complements",
    "Try + -ing can test a method; try + to-infinitive emphasises an attempt. Go on + -ing continues an activity; go on + to-infinitive introduces a later one. Mean + to-infinitive expresses intention; mean + -ing presents a consequence. Need + -ing can have passive meaning in relevant varieties and contexts.",
    "try **restarting** / try **to restart**",
    [
      "He went on **talking**, then went on **to discuss** the budget.",
      "The floor needs **cleaning** means it needs **to be cleaned**.",
    ],
    "Some contexts allow both complements with little practical difference. Do not force a dramatic meaning contrast where the surrounding situation does not support one.",
    nf,
  ),
  s(
    "passive-voice",
    "information",
    "passive-agent-and-focus",
    "Choosing active or passive and including the agent",
    "Active and passive clauses organise the same participants differently when the verb permits both. Passive is useful when the affected participant is the topic or the agent is unknown, unimportant or already understood. A by-phrase can restore the agent. Passive does not inherently remove responsibility or make writing more professional.",
    "The editor checked it. / It **was checked by the editor**.",
    [
      "**My bicycle was stolen** last night.",
      "**The report was written by Ana**, not by Bo.",
    ],
    "Some verbs do not form an ordinary corresponding passive, and some passives are idiomatic. Do not attempt to passivise a verb merely because a noun follows it.",
  ),
  s(
    "advanced-passives",
    "information",
    "get-passive-prepositional-passive",
    "Get-passives and prepositional passives",
    "Get + past participle can present an event affecting a subject, often in less formal language. Some prepositional verbs allow the complement of the preposition to become the passive subject, leaving the preposition at the end. The naturalness of such passives depends on the verb combination and what the discourse is about.",
    "She **got promoted**. / The issue **was dealt with**.",
    ["The children **were looked after**.", "He **got caught** in the rain."],
    "Get + adjective can describe becoming a state rather than a passive event: get hungry. Not every preposition phrase can naturally supply a passive subject.",
  ),
  s(
    "advanced-passives",
    "information",
    "passive-chains-and-causatives",
    "Passive infinitives, perfect forms and causative meanings",
    "Passive be can combine with modals, perfect and infinitive constructions. Read the chain one step at a time to identify time and voice. Have/get + object + participle commonly describes arranging a service, but have can also introduce an unwanted experience. Active causative patterns use a different arrangement.",
    "might **have been repaired** · needs **to be checked**",
    ["We **had the roof repaired**.", "She **had her bag stolen**."],
    "Had her bag stolen does not normally mean she arranged the theft. Context distinguishes a service causative from an affected-person experience.",
  ),
  s(
    "clefts-emphasis",
    "information",
    "fronting-and-end-focus",
    "Fronting, end focus and end weight",
    "English commonly begins with an established topic and places important new information later. A writer may front an object or adjunct to create a contrast or a frame. Long or complex phrases often work well near the end. These tendencies guide information flow, but they do not license arbitrary word order.",
    "**That book**, I enjoyed.",
    [
      "**In the next room**, a meeting was taking place.",
      "She explained to us **why the entire system had failed**.",
    ],
    "Fronting an object does not automatically require auxiliary inversion. Contrast That book I enjoyed with Never have I enjoyed a book so much.",
  ),
  s(
    "inversion",
    "information",
    "locative-and-conditional-inversion",
    "Locative inversion and conditional alternatives",
    "Some locative openings allow the main verb before a noun subject: on the hill stood a castle. This differs from auxiliary inversion after a negative expression. Formal conditional inversion can begin with had, were or should, each preserving a particular conditional meaning. Pronoun subjects behave differently in many locative patterns.",
    "On the wall **hung a portrait**.",
    [
      "**Should you need help**, call us.",
      "**Were she to resign**, we would need a replacement.",
    ],
    "With a personal pronoun, Here she comes is usual rather than Here comes she. Learn locative and negative inversion as separate constructions.",
  ),
  s(
    "clefts-emphasis",
    "information",
    "cleft-range",
    "It-clefts, what-clefts and reversed clefts",
    "Cleft constructions divide a message to highlight one part. An it-cleft focuses an expression after be and follows it with a clause. A what-cleft starts with a fused relative; reversing the order can change the focus. The highlighted part may be a person, thing, time, place or reason.",
    "**It was on Monday that** she called.",
    ["**What I need is a break**.", "**A break is what I need**."],
    "A cleft does not automatically contrast two named alternatives. Context may supply a correction, a new identification or an emphatic answer.",
  ),
  s(
    "there-is-there-are",
    "information",
    "existential-presentational-there",
    "Existential there, agreement and presentational constructions",
    "Existential there introduces the presence or occurrence of something, often new information. It is different from locative there, which points to a place. The construction can contain tense, modals or other verbs of appearance and existence. Formal agreement commonly reflects the following noun phrase; informal there’s before a plural is widespread.",
    "**There may be** a delay.",
    ["**There seems to be** a mistake.", "**There remain several questions**."],
    "There is is often awkward for introducing an already identified person in a neutral existence statement. Context can license definite noun phrases in lists and other special uses.",
  ),
];
