// A learner-facing crosswalk to the systems in Cambridge's comprehensive grammar.
// This is our organization, not a Cambridge-endorsed syllabus or copied textbook.
export const VERSION = "core-2026-09-v4";
export const domains = [
  [
    "foundations",
    "The building blocks",
    "Words, phrases, clauses and the jobs they do.",
    "1–2",
  ],
  [
    "verbs",
    "Verbs, tense, aspect and modality",
    "How verb phrases express time, viewpoint, possibility and necessity.",
    "3",
  ],
  [
    "clause-patterns",
    "Clause patterns and complements",
    "Subjects, objects, complements, valency and agreement.",
    "4",
  ],
  [
    "noun-phrases",
    "Nouns, articles and determiners",
    "Number, countability, possession, reference and quantity.",
    "5",
  ],
  [
    "modifiers",
    "Adjectives and adverbs",
    "Description, position, degree and the reach of a modifier.",
    "6",
  ],
  [
    "prepositions",
    "Prepositions and particles",
    "Relations, complements and multi-word combinations.",
    "7",
  ],
  [
    "adjuncts",
    "Time, place, reason and other adjuncts",
    "How phrases and clauses add circumstances and connect events.",
    "8",
  ],
  [
    "negation",
    "Negation and negative meaning",
    "What is denied, how negatives are built and how their meanings interact.",
    "9",
  ],
  [
    "sentence-types",
    "Statements, questions, commands and exclamations",
    "Sentence form, communicative purpose and responses.",
    "10",
  ],
  [
    "content-clauses",
    "Content clauses and reported language",
    "Embedding statements, questions, instructions and other messages.",
    "11",
  ],
  [
    "relatives",
    "Relative constructions",
    "Identifying, adding information and connecting a gap to its referent.",
    "12",
  ],
  [
    "comparison",
    "Comparison and degree",
    "Equality, difference, limits, proportions and comparative clauses.",
    "13",
  ],
  [
    "nonfinite",
    "Non-finite and verbless clauses",
    "Infinitives, participles, understood subjects and clauses without a verb.",
    "14",
  ],
  [
    "coordination",
    "Coordination and added information",
    "Joining equal units, sharing material and adding supplements.",
    "15",
  ],
  [
    "information",
    "Focus and information structure",
    "Choosing the starting point, emphasis and the order of known and new information.",
    "16",
  ],
  [
    "reference",
    "Reference, deixis and cohesion",
    "Tracking people, things, time and place across sentences.",
    "17",
  ],
  [
    "inflection",
    "Word forms and inflection",
    "Regular endings, irregular forms, case and spelling changes.",
    "18",
  ],
  [
    "word-formation",
    "Word formation",
    "Prefixes, suffixes, compounds, conversion and lexical patterns.",
    "19",
  ],
  [
    "punctuation",
    "Punctuation and written conventions",
    "Marking sentence boundaries, quotations and relationships in writing.",
    "20",
  ],
  [
    "usage",
    "Spoken grammar, register and variation",
    "Conversation, politeness, formal writing and standard regional differences.",
    "cross-cutting",
  ],
].map(([id, title, summary, referenceChapters]) => ({
  id,
  title,
  summary,
  referenceChapters,
}));
export const topicDomains = {
  "sentence-structure": "foundations",
  "nouns-and-plurals": "inflection",
  "pronouns-and-possessive-determiners": "reference",
  "present-simple-be": "verbs",
  demonstratives: "reference",
  articles: "noun-phrases",
  "possessive-s": "noun-phrases",
  "there-is-there-are": "information",
  "have-got": "verbs",
  "present-simple": "verbs",
  "question-forms": "sentence-types",
  imperatives: "sentence-types",
  "present-continuous": "verbs",
  "countable-uncountable": "noun-phrases",
  "small-quantities": "noun-phrases",
  "determiners-quantifiers": "noun-phrases",
  "prepositions-of-time": "prepositions",
  "prepositions-of-place": "prepositions",
  "movement-prepositions": "prepositions",
  "articles-place-names": "noun-phrases",
  "adjective-order": "modifiers",
  "ed-ing-adjectives": "modifiers",
  "comparatives-and-superlatives": "comparison",
  "adverbs-position": "modifiers",
  "modals-ability": "verbs",
  "past-simple": "verbs",
  "past-continuous": "verbs",
  "future-forms": "verbs",
  "present-perfect": "verbs",
  "stative-dynamic": "verbs",
  "present-perfect-continuous": "verbs",
  "past-perfect": "verbs",
  "past-perfect-continuous": "verbs",
  "future-perfect-continuous": "verbs",
  "past-habits": "verbs",
  "infinitive-of-purpose": "nonfinite",
  "verb-patterns": "nonfinite",
  "dependent-prepositions": "prepositions",
  "modal-obligation": "verbs",
  "modal-deduction": "verbs",
  "past-modals": "verbs",
  conditionals: "adjuncts",
  "third-mixed-conditionals": "adjuncts",
  wishes: "verbs",
  "linking-clauses": "adjuncts",
  "contrast-concession": "adjuncts",
  "degree-comparison": "comparison",
  "passive-voice": "information",
  "relative-clauses": "relatives",
  "reported-statements": "content-clauses",
  "reported-questions": "content-clauses",
  "question-tags": "sentence-types",
  "reflexive-reciprocal": "reference",
  "verb-pattern-meaning": "nonfinite",
  "phrasal-verbs": "prepositions",
  "noun-clauses": "content-clauses",
  "punctuation-clauses": "punctuation",
  "agreement-advanced": "clause-patterns",
  "advanced-passives": "information",
  "reporting-verb-patterns": "content-clauses",
  "participle-clauses": "nonfinite",
  inversion: "information",
  "clefts-emphasis": "information",
  "ellipsis-substitution": "reference",
  "unreal-subjunctive": "verbs",
  "noun-modifiers": "word-formation",
  "register-variation": "usage",
};
export const sources = [
  {
    id: "cambridge-comprehensive-scope",
    title: "The Cambridge Grammar of the English Language: contents",
    publisher: "Cambridge University Press",
    url: "https://www.cambridge.org/features/linguistics/cgel/contents.htm",
    use: "Published subject-area crosswalk only. Original learner explanations; no textbook chapter or exercise reproduced. The crosswalk is not publisher approval.",
    reviewedOn: "2026-09-13",
  },
  {
    id: "cambridge-spoken",
    title: "Spoken English",
    publisher: "Cambridge English Grammar Today",
    url: "https://dictionary.cambridge.org/grammar/british-grammar/spoken-english",
    use: "Guidance on spoken grammatical structures; original explanations and examples.",
    reviewedOn: "2026-09-13",
  },
  {
    id: "cambridge-hedges",
    title: "Hedges",
    publisher: "Cambridge English Grammar Today",
    url: "https://dictionary.cambridge.org/grammar/british-grammar/hedges-just",
    use: "Guidance on softening and stance; original explanations and examples.",
    reviewedOn: "2026-09-13",
  },
  {
    id: "cambridge-headers-tails",
    title: "Headers and tails",
    publisher: "Cambridge English Grammar Today",
    url: "https://dictionary.cambridge.org/grammar/british-grammar/headers-and-tails",
    use: "Guidance on spoken information structure; original explanations and examples.",
    reviewedOn: "2026-09-13",
  },
  {
    id: "cambridge-negation",
    title: "Negation",
    publisher: "Cambridge English Grammar Today",
    url: "https://dictionary.cambridge.org/grammar/british-grammar/negation_2",
    use: "Guidance on negative constructions; original explanations and examples.",
    reviewedOn: "2026-09-13",
  },
  {
    id: "cambridge-word-formation",
    title: "Word formation",
    publisher: "Cambridge English Grammar Today",
    url: "https://dictionary.cambridge.org/us/grammar/british-grammar/word-formation",
    use: "Scope and terminology for morphological processes; original explanations and examples.",
    reviewedOn: "2026-09-13",
  },
  {
    id: "cambridge-nonfinite-scope",
    title: "Non-finite and verbless clauses: chapter contents",
    publisher: "Cambridge University Press",
    url: "https://www.cambridge.org/assets/linguistics/cgel/chap14_contents.pdf",
    use: "Published subtopic crosswalk only; original learner explanations and examples.",
    reviewedOn: "2026-09-13",
  },
];
export function section(
  topicSlug,
  domain,
  id,
  title,
  explanation,
  pattern,
  examples,
  edge,
  referenceIds = ["cambridge-comprehensive-scope"],
) {
  return {
    topicSlug,
    domain,
    id,
    title,
    explanation,
    pattern,
    examples,
    commonMistakes: [edge],
    referenceIds,
  };
}
