import { section as s } from "./domains.mjs";
const neg = ["cambridge-negation", "cambridge-comprehensive-scope"];
export const sections = [
  s(
    "modal-obligation",
    "negation",
    "negation-auxiliaries",
    "Building negatives with and without auxiliaries",
    "In an ordinary finite negative, not follows the first auxiliary. If a lexical verb has no auxiliary, present and past simple normally add do. Be makes its own negative, and imperative be uses do not. Non-finite constructions can place not before the infinitive or participle. Identify the construction before placing the negative.",
    "does **not** know · has **not** been told",
    ["**Do not be** late.", "She asked us **not to wait**."],
    "A negative prefix changes a word, while not can negate a phrase or clause. Unhappy and not happy can differ in implication.",
    neg,
  ),
  s(
    "determiners-quantifiers",
    "negation",
    "no-none-not-any",
    "No, none, nobody and not…any",
    "No is a determiner before a noun. None can stand alone or occur with of. Nobody, nothing and nowhere incorporate negative meaning. A negative verb with any-forms can often express a related message, but the focus and style may differ. Standard clauses ordinarily avoid a second negative expressing the same denial.",
    "**No visitors** arrived. / **Nobody** arrived.",
    [
      "There isn’t **any milk**. / There is **no milk**.",
      "**None of these keys** fits the lock.",
    ],
    "With none of + plural noun, singular and plural agreement are both found according to emphasis and register. Avoid teaching only one as universally grammatical.",
    neg,
  ),
  s(
    "determiners-quantifiers",
    "negation",
    "negative-scope",
    "The scope of a negative",
    "Scope is the part of the meaning affected by a negative. Position and stress can change whether a whole event, an amount, a frequency or a reason is denied. A negative combined with all, every, always or necessarily often leaves some positive cases possible. Rephrase when the intended scope is unclear.",
    "**Not all** passed ≠ **None** passed",
    [
      "She does **not always** drive means there are occasions when she does not.",
      "It is **not necessarily** expensive means expense is not guaranteed.",
    ],
    "All the guests didn’t come can be ambiguous in ordinary use. Write Not all the guests came or None of the guests came to state the intended meaning.",
    neg,
  ),
  s(
    "modal-obligation",
    "negation",
    "modal-negative-scope",
    "Mustn’t, don’t have to and can’t: what is negated?",
    "A modal and a negative can interact in different ways. Must not normally prohibits an action; not have to denies necessity. Cannot denies ability, permission or possibility according to context. May not can deny permission or describe a negative possibility. Identify whether the negative affects the event or the modal judgement.",
    "**must not go** / **do not have to go**",
    [
      "You **mustn’t enter**: entry is prohibited.",
      "She **may not come**: perhaps she will stay away.",
    ],
    "May not come can also mean that permission is refused in a suitable context. An explanation should state the intended reading rather than pretend the words have only one meaning.",
    neg,
  ),
  s(
    "adverbs-position",
    "negation",
    "near-negatives-polarity",
    "Hardly, scarcely, seldom and negative-polarity words",
    "Hardly, scarcely, rarely and seldom have negative or near-negative meaning without not. They often combine with any or ever and usually take positive question tags. Some expressions prefer negative, interrogative or conditional environments. Ever, any and at all are useful examples, although each has other licensed uses.",
    "She **hardly ever** complains.",
    ["There was **hardly any** traffic.", "He **seldom visits**, does he?"],
    "Hardly means almost not; hard describes effort or intensity. They are not interchangeable adjective/adverb forms.",
    neg,
  ),
  s(
    "reported-statements",
    "negation",
    "negative-raising",
    "I don’t think and the location of the negative",
    "With verbs such as think, believe and suppose, English often places the negative in the main clause while conveying a negative judgement about the embedded proposition. I don’t think she is ready usually suggests that the speaker thinks she is not ready, but context can instead deny having a settled belief.",
    "I **don’t think** it will work.",
    [
      "I **don’t suppose** they will agree.",
      "I **think it won’t work** makes the negative prediction more explicit.",
    ],
    "This pattern does not apply freely to every reporting verb. I didn’t say he left denies the act of saying it and does not automatically mean I said he didn’t leave.",
    neg,
  ),
  s(
    "register-variation",
    "negation",
    "double-negation-and-concord",
    "Double negation, negative concord and litotes",
    "Two negatives can cancel or soften one another in standard English, as in not impossible. In some dialects, multiple negative forms instead express a single negative meaning; this systematic pattern is called negative concord. Recognising dialect grammar is different from choosing the standard form expected in a formal document.",
    "**not impossible** / **not without difficulty**",
    [
      "The result was **not unexpected**.",
      "Standard formal wording: **I didn’t see anything**.",
    ],
    "Not bad is often praise rather than a literal claim of neutrality. Context determines the pragmatic force of a softened negative.",
    neg,
  ),
  s(
    "adjective-order",
    "modifiers",
    "adjective-complements",
    "Adjectives with complements and position restrictions",
    "Adjectives can take preposition phrases, infinitives or clauses as complements. Some normally occur after a linking verb rather than before a noun, while others strongly prefer attributive use. A complemented adjective phrase often follows its noun. Learn the adjective and the complement pattern together.",
    "**afraid of** dogs · **eager to** help",
    [
      "The people **responsible for the delay** apologised.",
      "The child is **asleep**, but an **asleep child** is not the usual pattern.",
    ],
    "Related adjectives may have different patterns: interested in, keen on, eager to. Similar meaning does not guarantee identical complementation.",
  ),
  s(
    "adjective-order",
    "modifiers",
    "postpositive-and-substantive-adjectives",
    "Adjectives after nouns and adjectives naming groups",
    "Adjectives follow indefinite pronouns such as something and anyone. They also occur after nouns in some fixed expressions or when a following complement makes the phrase long. The + adjective can refer to a group of people or an abstract category, but number and meaning depend on the expression.",
    "something **useful** · the **rich**",
    [
      "We need a room **large enough for everyone**.",
      "**The elderly** may need additional support.",
    ],
    "The rich normally has plural human reference; the unknown can have abstract singular reference. Do not add an ordinary plural -s to rich in this group use.",
  ),
  s(
    "adjective-order",
    "modifiers",
    "adjective-position-meaning",
    "When adjective position changes meaning",
    "Some adjectives change interpretation according to position. A concerned parent is worried, while the people concerned are those involved. Present, responsible and involved show similar contrasts in suitable contexts. Position is therefore part of meaning, not merely a stylistic option. Use a fuller phrase when a short adjective is ambiguous.",
    "the **people concerned** / **concerned people**",
    [
      "The **present manager** means the current manager.",
      "The **members present** means the members who attended.",
    ],
    "The contrast depends on the particular adjective; it is not a general rule that every adjective changes meaning before and after its noun.",
  ),
  s(
    "ed-ing-adjectives",
    "modifiers",
    "participial-adjective-versus-verb",
    "Participles as adjectives or parts of verb phrases",
    "An -ed or -ing form can function as an adjective or as part of a verb phrase. Its complements and meaning help identify its role. Some expressions allow both a state and an event reading. Degree modification can suggest adjective status, while an agent by-phrase often supports a passive event reading.",
    "The door **was closed**: state or event?",
    [
      "The story was **very amusing**.",
      "The host was **amusing the children**.",
    ],
    "No single surface test settles every case. Do not treat every -ed adjective as a passive verb or every -ing word as present continuous.",
  ),
  s(
    "adverbs-position",
    "modifiers",
    "adverb-scope-and-focus",
    "Only, even, also and the reach of an adverb",
    "Focusing adverbs select a part of the message for contrast. Moving only can change whether the restriction concerns a person, action, object or time; stress also helps. Even marks something as unexpected on a relevant scale, while also adds an alternative. Put the adverb where its intended scope is easiest to recover.",
    "**Only Maya** borrowed it. / Maya borrowed **only it**.",
    [
      "I **only borrowed** the book; I did not buy it.",
      "**Even the expert** was surprised.",
    ],
    "An adverb’s nearest word is not always its only possible focus in speech. In careful writing, choose placement that reduces ambiguity.",
  ),
  s(
    "adverbs-position",
    "modifiers",
    "sentence-adverbs-and-flat-adverbs",
    "Sentence adverbs, viewpoint adverbs and flat forms",
    "Some adverbs comment on a whole proposition or on the act of speaking: probably, fortunately, frankly. Others describe manner, degree or a particular viewpoint. Several have the same form as an adjective, such as fast and hard; a related -ly form may change meaning. Identify the job of the word in the sentence.",
    "**Frankly**, I disagree. / She answered **frankly**.",
    [
      "He arrived **late**, but I haven’t seen him **lately**.",
      "The team played **well**, although the pitch was **bad**.",
    ],
    "Good is normally an adjective; well commonly describes how an action is done, but well can also be an adjective meaning healthy.",
  ),
  s(
    "degree-comparison",
    "comparison",
    "gradable-nongradable",
    "Gradable adjectives, extremes and intensifiers",
    "Gradable adjectives allow degrees, such as fairly cold or very cold. Some adjectives express an extreme or a category and typically combine with different intensifiers, such as absolutely exhausted or completely wrong. Real usage can extend or reinterpret these meanings. Treat the combinations as meaning-sensitive preferences rather than an absolute ban on creativity.",
    "**very tired** / **absolutely exhausted**",
    [
      "The answer is **completely wrong**.",
      "The room was **rather small** but **quite comfortable**.",
    ],
    "Quite can mean fairly or completely depending on the adjective, dialect and stress. Learn it in a complete expression.",
  ),
  s(
    "comparatives-and-superlatives",
    "comparison",
    "comparative-clauses-ellipsis",
    "Comparative clauses and omitted material",
    "Than and as can introduce clauses in which repeated material is omitted. A remaining pronoun may have different forms depending on whether it is interpreted as part of a clause or as a complement in a shorter construction. Expanding the comparison makes the roles clear and can remove ambiguity.",
    "She is taller **than I am** / **than me**.",
    [
      "He likes football more than **I do**.",
      "She helped Alex more than **she helped me**.",
    ],
    "He likes her more than me can compare the people he likes or the people who like her. Expand the clause to state which comparison you mean.",
  ),
  s(
    "degree-comparison",
    "comparison",
    "progressive-proportional-comparison",
    "More and more, the more…the more and proportions",
    "A repeated comparative describes a developing change. Paired the + comparative clauses link two changing quantities or degrees. Multipliers and fractions compare amounts or dimensions using expressions such as twice as much or half as long. Ensure the construction matches whether the noun is countable or non-count.",
    "**The more** you practise, **the easier** it becomes.",
    [
      "It is getting **colder and colder**.",
      "This route is **twice as long as** the other.",
    ],
    "Twice longer than can be interpreted inconsistently. Twice as long as is clearer when the intended ratio is two to one.",
  ),
  s(
    "comparatives-and-superlatives",
    "comparison",
    "less-fewer-superlative-scope",
    "Less, fewer and the comparison set",
    "Fewer normally modifies plural count nouns; less normally modifies non-count quantities. Less also appears with measurements and fixed numerical expressions. A superlative selects an extreme within an understood group, so the comparison set must be clear. Comparative forms can compare two members or two states of the same thing.",
    "**fewer mistakes** / **less work**",
    [
      "It took **less than ten minutes**.",
      "She is **the youngest in the team**.",
    ],
    "Fewer is useful for separate countable items, but a blanket ban on less before every number misrepresents ordinary measurement expressions.",
  ),
  s(
    "degree-comparison",
    "comparison",
    "too-enough-result-infinitives",
    "Too and enough with result infinitives",
    "Too marks an excessive degree relative to a goal; enough marks sufficiency. Both can introduce an infinitive explaining the relevant possibility. A for-phrase can identify the infinitive’s subject. In some adjective constructions, the understood object of the infinitive is the main-clause subject.",
    "The box is **too heavy for me to lift**.",
    [
      "She is **old enough to travel alone**.",
      "The instructions are **clear enough to follow**.",
    ],
    "Do not add an unnecessary object pronoun: This box is too heavy to lift, not too heavy to lift it, in the ordinary linked-object construction.",
  ),
  s(
    "prepositions-of-place",
    "prepositions",
    "preposition-complements",
    "Prepositions with nouns, pronouns and clauses",
    "A preposition can take a noun phrase, an object pronoun or an -ing clause as its complement. Some also take an embedded interrogative clause. A preposition phrase can function as a complement or a modifier. A familiar word such as to can instead be an infinitive marker in another construction.",
    "after **lunch** / after **leaving**",
    [
      "She is interested **in how it works**.",
      "I look forward **to meeting** you.",
    ],
    "Distinguish preposition to from infinitival to: look forward to meeting uses a preposition, while hope to meet uses an infinitive marker.",
  ),
  s(
    "dependent-prepositions",
    "prepositions",
    "stranding-and-fronting",
    "Preposition stranding and formal fronting",
    "A preposition can remain at the end of a question or relative clause when its complement is understood from an earlier expression. In more formal constructions, it may move before whom or which. Both are established standard patterns. The verb and preposition combination can restrict which alternative sounds natural.",
    "Who did you speak **to**? / **To whom** did you speak?",
    [
      "That is the person **I worked with**.",
      "That is the person **with whom I worked**.",
    ],
    "Ending a clause with a preposition is not inherently wrong. Avoid changing a natural standard sentence solely to satisfy that mistaken blanket prohibition.",
  ),
  s(
    "movement-prepositions",
    "prepositions",
    "spatial-relations-contrasts",
    "Across, through, over, along, beyond and past",
    "Spatial prepositions select different aspects of a route or location. Across crosses a surface or area; through presents an interior or passage; along follows a line. Over may describe a higher position or a route crossing above something. Beyond and past relate a point to a reference boundary. Real scenes can support more than one description.",
    "**through** the tunnel / **across** the bridge",
    [
      "We walked **along the river**.",
      "The village lies **beyond the hills**.",
    ],
    "Above and over overlap, but not everywhere: an aircraft flew over the city describes a route, while a light above the desk describes relative position.",
  ),
  s(
    "prepositions-of-time",
    "prepositions",
    "time-preposition-contrasts",
    "During, for, since, by, until, within and throughout",
    "During locates an event within a period; for measures duration; since identifies a starting point. By sets a deadline, until marks continuation, and within gives an allowed interval. Throughout presents coverage over a whole period. Decide what relation is intended rather than translating a preposition word for word.",
    "finish **by Friday** / stay **until Friday**",
    [
      "She slept **during the film** for twenty minutes.",
      "Please reply **within three days**.",
    ],
    "By Friday does not mean continuing until Friday. Since can combine with different tense frames and does not itself guarantee a present-perfect construction.",
  ),
  s(
    "phrasal-verbs",
    "prepositions",
    "multiword-verb-types",
    "Phrasal, prepositional and phrasal-prepositional verbs",
    "A particle verb such as turn off may permit an object between its parts; a prepositional verb such as look after keeps its preposition before its complement. Some combinations contain both a particle and a preposition, as in put up with. Their meanings can be idiomatic, so learn meaning, transitivity and order together.",
    "turn **it** off / look after **it**",
    [
      "Please **put up with the noise** for a moment.",
      "The engine **broke down**; it has no object here.",
    ],
    "A pronoun goes between a separable particle verb and particle, but not into a prepositional verb: turn it off, not look it after.",
  ),
];
