import { section as s } from "./domains.mjs";
export const sections = [
  s(
    "nouns-and-plurals",
    "noun-phrases",
    "noun-categories",
    "Common, proper, concrete, abstract and collective nouns",
    "A common noun names a class; a proper name identifies a particular person, place or institution. Concrete and abstract describe kinds of meaning, while collective describes a group treated as a unit or as members. These categories overlap and do not directly determine countability. A name can also acquire a descriptive or count use.",
    "a **city** / **Lisbon** · a **team** / **courage**",
    [
      "We need **an idea**, but we need **advice**.",
      "There are **two Alexes** in our class.",
    ],
    "An abstract noun can be countable: a decision, two hopes. A concrete noun can be uncountable: furniture, water.",
  ),
  s(
    "countable-uncountable",
    "noun-phrases",
    "countability-shifts",
    "When a noun changes between count and non-count uses",
    "Countability belongs to a noun’s use in context, not only its dictionary entry. A non-count substance can become a count serving or type; an abstract quality can become an instance. Some nouns change meaning: paper can mean a material, a newspaper or a scholarly article. Learn the associated determiners with each sense.",
    "**coffee** / **two coffees** · **experience** / **an experience**",
    [
      "We bought **glass** for the window. / She broke **a glass**.",
      "He has **experience**. / It was **an unusual experience**.",
    ],
    "A change of meaning can license a count form; it does not make every uncountable noun freely plural. Ordinary information and advice remain non-count.",
  ),
  s(
    "countable-uncountable",
    "noun-phrases",
    "partitives-and-measures",
    "Pieces, pairs, quantities and partitive expressions",
    "A partitive expression identifies a unit or amount of something. The unit noun can be counted and determines agreement in an ordinary unit-based phrase. Choose units appropriate to the substance or object. Some plural-only objects are counted with pair; containers can stand for their contents.",
    "a **piece of** advice · two **pairs of** scissors",
    [
      "**Two bottles of water are** on the table.",
      "I need **a sheet of paper** and **a piece of equipment**.",
    ],
    "Do not add plural endings to the non-count noun just because the unit is plural: three pieces of furniture, not three furnitures.",
  ),
  s(
    "nouns-and-plurals",
    "inflection",
    "plural-only-and-singular-looking",
    "Plural-only nouns and misleading endings",
    "Some nouns normally occur in plural form, such as scissors and trousers. Others end in s but commonly take singular agreement, such as news and mathematics in their ordinary subject-area use. Some have identical singular and plural forms. Determine the meaning and noun pattern rather than relying on the last letter.",
    "The **news is** good. / These **scissors are** sharp.",
    [
      "**One species is** endangered; **several species are** protected.",
      "**A pair of trousers is** missing.",
    ],
    "Statistics can name a field of study or plural numerical facts: Statistics is useful; these statistics are surprising.",
  ),
  s(
    "nouns-and-plurals",
    "inflection",
    "compound-and-borrowed-plurals",
    "Compound nouns and borrowed plurals",
    "The head of a compound normally receives plural marking: mothers-in-law, passers-by. Some borrowed nouns retain a foreign plural, while others have an English plural or allow alternatives. Usage varies by field and formality, so a current dictionary helps with individual words. The rule is a system with lexical exceptions.",
    "mother**s**-in-law · analys**is** → analys**es**",
    [
      "One **criterion**, several **criteria**.",
      "Two **brothers-in-law** came to visit.",
    ],
    "Forms such as formulas/formulae and indexes/indices vary by context. Do not label one established alternative universally wrong.",
  ),
  s(
    "articles",
    "noun-phrases",
    "generic-reference",
    "General reference: a tiger, the tiger and tigers",
    "General statements can use different noun-phrase types. A plural without an article is a common way to refer to a class generally. A/an can describe a representative member. The + singular can refer to a species, invention or class in suitable formal contexts. These forms overlap but are not interchangeable in every predicate.",
    "**Tigers** need space. / **A tiger** is a powerful animal.",
    [
      "**The telephone** changed communication.",
      "**Music** can affect our mood.",
    ],
    "A representative individual cannot replace a species-level reference mechanically: The tiger is endangered does not mean that one unspecified tiger is endangered.",
  ),
  s(
    "articles",
    "noun-phrases",
    "definiteness-beyond-mention",
    "Shared knowledge, unique reference and associative the",
    "The signals that the intended referent can be identified, not merely that a noun has appeared before. Identification can come from the situation, shared knowledge, an attached description or association with something already introduced. A/an introduces one member without requiring the listener to identify which.",
    "We entered a house. **The roof** was leaking.",
    [
      "Please close **the door**.",
      "She is **the person who called yesterday**.",
    ],
    "A defining phrase does not always force the: I need a book that explains this introduces any suitable book rather than a uniquely identified one.",
  ),
  s(
    "articles-place-names",
    "noun-phrases",
    "institutional-articles",
    "Institutional purpose, locations and activities",
    "School, prison, church, bed and some other nouns can take no article in established expressions about their usual purpose. The same noun can take the when a particular building or object is meant. Hospital differs notably across British and American usage. These are conventional patterns, so they must be learned individually.",
    "at **school** / outside **the school**",
    [
      "The children are **at school**; their father is **at the school** for a meeting.",
      "She went **to bed** early; the cat hid **under the bed**.",
    ],
    "The contrast is not always purpose versus building for every noun. We normally say at university in British English but at the office in both major varieties.",
  ),
  s(
    "articles-place-names",
    "noun-phrases",
    "article-conventions",
    "Meals, transport, illnesses, languages and titles",
    "Many familiar expressions use no article: have breakfast, travel by bus, speak Spanish. Modification, specificity or a count meaning can introduce an article: a large breakfast, the bus we caught. Titles before a personal name often omit the article. Illness names have individual patterns rather than one general rule.",
    "by **train** / on **the train**",
    [
      "We had **breakfast**. / We enjoyed **a late breakfast**.",
      "**Professor Silva** spoke about **the Spanish language**.",
    ],
    "A headache and a cold take an article in ordinary use, while flu/the flu varies by variety. Do not extend the meal or transport convention to unrelated nouns.",
  ),
  s(
    "possessive-s",
    "noun-phrases",
    "genitive-alternatives",
    "Possessive forms, of-phrases and double genitives",
    "The genitive can express possession, origin, relationship or time. ’s often works well with people, groups and time expressions; an of-phrase is useful for many inanimate relationships and longer modifiers. An independent possessive after of can select one from a set: a friend of mine. The choice also affects focus and rhythm.",
    "Maya**’s** idea / the end **of** the road",
    ["It is **a neighbour of ours**.", "We need **a day’s rest**."],
    "A photo of Maya depicts her; a photo of Maya’s belongs to or is associated with her. The two expressions need not describe the same relationship.",
  ),
  s(
    "possessive-s",
    "noun-phrases",
    "joint-and-independent-possession",
    "Joint owners, separate owners and omitted nouns",
    "A shared possession commonly has one genitive ending after the coordinated owners. Separate possessions can mark each owner separately. A possessive can stand alone when its noun is recoverable, especially for homes and businesses. With a long possessor phrase, ’s attaches at its right edge in ordinary phrasal genitives.",
    "**Ana and Bo’s** house / **Ana’s and Bo’s** houses",
    ["We met **at my uncle’s**.", "That is **the woman next door’s** bicycle."],
    "Long phrasal genitives can be hard to read; rephrase when the relationship becomes unclear. Plural possessive spelling still depends on the plural noun’s ending.",
  ),
  s(
    "determiners-quantifiers",
    "noun-phrases",
    "determiner-order",
    "Determiner slots, numbers and predeterminers",
    "A noun phrase usually has one central determiner, such as the, this or my. Some quantity words occur before it; numbers and ordinal expressions normally follow it. The order reflects the different jobs: identifying the group, locating an item within it, then counting or describing. Not every modifier belongs to the same slot.",
    "**all my three** children · **the first two** pages",
    [
      "**Both these** windows are open.",
      "She read **my next three** messages.",
    ],
    "Do not stack ordinary central determiners: the my book and this a chair are not standard noun phrases. Use my book or this chair.",
  ),
  s(
    "determiners-quantifiers",
    "noun-phrases",
    "some-any-context",
    "Some, any and their compound pronouns",
    "Some often presents an unspecified amount positively, including offers and requests expecting acceptance. Any often appears in open questions and negatives, but it also means unrestricted choice in positive clauses. Someone, anyone, something and anything show related patterns. The speaker’s intended meaning matters more than a positive/negative shortcut.",
    "Would you like **some**? / Choose **any** one.",
    ["Is there **anything** I can do?", "**Anyone** with a ticket may enter."],
    "I didn’t buy any books normally means zero purchases. I didn’t buy some of the books means that particular members of a set were left unbought.",
  ),
  s(
    "determiners-quantifiers",
    "noun-phrases",
    "quantifier-range",
    "Much, many, a lot, enough, several and plenty",
    "Many and several select plural count nouns; much selects non-count nouns. A lot of and plenty of work with both. Enough marks sufficiency and precedes a noun. Much is common in questions and negatives; a lot of is often more natural in ordinary affirmative conversation. Formal and modified uses allow much in affirmatives.",
    "**many books** / **much time** / **enough room**",
    [
      "We have **plenty of chairs** but **little space**.",
      "There has been **much discussion** about the plan.",
    ],
    "Few/little and a few/a little differ in how they present the amount, not simply in whether the amount is mathematically small.",
  ),
  s(
    "determiners-quantifiers",
    "noun-phrases",
    "distributive-partitive-numbers",
    "Each, every, all, whole, half and percentages",
    "Each foregrounds members individually; every covers all members of a set. All and whole can present completeness in different noun patterns. Fractions and percentages can refer to count or non-count quantities. In expressions such as half of the water or half of the students, the following noun often determines the practical agreement choice.",
    "**the whole day** / **all day**",
    [
      "**Half the cake is** left. / **Half the guests are** here.",
      "**Every two weeks**, we meet again.",
    ],
    "Every is normally followed by a singular count noun, but every + number + plural noun expresses intervals: every three days.",
  ),
  s(
    "pronouns-and-possessive-determiners",
    "reference",
    "pronoun-reference-and-case",
    "Pronoun case, antecedents and clear reference",
    "Subject and object pronoun forms depend on grammatical position, not on politeness or proximity to a name. An antecedent supplies the intended referent, but a pronoun can also refer to the shared situation. In coordination, check each pronoun’s role. Repeating a name can be clearer than leaving two possible antecedents.",
    "**She and I** arrived. / They called **her and me**.",
    [
      "The teacher spoke to **Alex and me**.",
      "When Omar met Luis, **Omar** was carrying the parcel.",
    ],
    "Between you and me uses object case after a preposition. Informal It’s me is normal contemporary English; It is I belongs to a more formal register.",
  ),
  s(
    "pronouns-and-possessive-determiners",
    "reference",
    "singular-they-generic-reference",
    "Singular they, generic you and indefinite reference",
    "They can refer to one person whose gender is unknown, irrelevant or specified that way; the verb still uses the ordinary they form. Generic you refers to people generally, while formal one can do similar work. Indefinite pronouns such as everyone usually take singular agreement but can be referred back to with they.",
    "Someone **has** left **their** bag.",
    [
      "If a visitor arrives, ask whether **they are** expected.",
      "**You** never know what will happen.",
    ],
    "Do not switch unpredictably between one, you and they in the same generalisation. Choose a consistent reference pattern and a suitable register.",
  ),
  s(
    "pronouns-and-possessive-determiners",
    "reference",
    "dummy-it-and-reference",
    "Referential it, weather it and anticipatory it",
    "It can refer to an earlier noun or situation, but it also fills a subject position without naming an object, as in weather, distance and time expressions. Anticipatory it lets a longer clause appear later. Distinguish these uses from demonstrative this or that, which can point to and frame a whole idea.",
    "**It** is raining. / **It** is useful to revise.",
    [
      "**It** is five kilometres to the village.",
      "She lost her ticket. **That** caused a delay.",
    ],
    "Weather it does not refer to a hidden person or thing. English usually requires this grammatical subject even when another language omits it.",
  ),
  s(
    "demonstratives",
    "reference",
    "deixis-and-viewpoint",
    "Deixis: here, there, now, then, come and go",
    "Deictic expressions depend on the speaker’s or a represented person’s viewpoint. Here and now identify a location and time relative to that viewpoint; this and that can organise a discussion as well as indicate physical distance. Come and go also reflect a chosen centre, which can shift to a listener or a story character.",
    "**here / there** · **now / then** · **this / that**",
    [
      "I’ll **come to your office** tomorrow.",
      "In that letter, **tomorrow** meant the day after it was written.",
    ],
    "Quoted language preserves the original viewpoint; a later report may need different time and place words. There is no automatic replacement without context.",
  ),
  s(
    "reflexive-reciprocal",
    "reference",
    "reflexive-emphasis-and-by",
    "Reflexive, emphatic and by-myself meanings",
    "A reflexive pronoun can be an object referring back to the local subject. The same form can add emphasis, and by + reflexive commonly means alone or without help. These meanings are related but grammatically distinct. An ordinary object pronoun points to a different person unless a special context supplies another interpretation.",
    "She hurt **herself**. / She **herself** explained it.",
    ["I repaired it **myself**.", "The children travelled **by themselves**."],
    "Do not use myself merely as a more formal substitute for me: please contact Sam or me. Reflexive licensing depends on the structure.",
  ),
  s(
    "ellipsis-substitution",
    "reference",
    "one-ones-and-other",
    "One, ones, other, another and the others",
    "One and ones can replace a count noun while retaining its modifiers. Another usually means one additional or different member; other precedes a plural or non-count noun, while others stands without a following noun. The identifies a contextually recoverable remainder or alternative. These forms combine reference with number and definiteness.",
    "the red **one** / the smaller **ones**",
    [
      "Some stayed; **the others** left.",
      "I’d like **another cup**, but no **other food**.",
    ],
    "One does not normally replace an ordinary non-count noun: I need fresh water, not a cold one, unless one means a count serving or a container in context.",
  ),
  s(
    "ellipsis-substitution",
    "reference",
    "anaphora-cataphora",
    "Looking backward and forward in a text",
    "Reference can look back to an earlier expression, forward to an explanation, or outward to the shared situation. A repeated noun, pronoun or demonstrative links clauses into a coherent text. Keep the intended referent close enough and specific enough for the reader to identify it. Whole propositions can also be referred to with this, that or so.",
    "**This** is the problem: the key does not fit.",
    [
      "Although **she** was tired, **Nadia** finished the report.",
      "The train was cancelled. **That** changed our plans.",
    ],
    "A pronoun before a name is possible in some structures, but forward reference is not unrestricted: He says that Tom is ready normally does not make he and Tom the same person.",
  ),
];
