import { section as s } from "./domains.mjs";
export const sections = [
  s(
    "sentence-structure",
    "foundations",
    "form-and-function",
    "Word class is different from sentence function",
    "A word class tells you what kind of word something is; a function tells you its job in a particular construction. A noun phrase can be a subject, an object or a complement. The same spelling can belong to different classes. Identify the surrounding pattern instead of assigning one permanent class from the dictionary.",
    "**class**: noun phrase · **function**: subject or object",
    [
      "**The runner** waved. / We greeted **the runner**.",
      "They **work** here. / Their **work** is useful.",
    ],
    "A subject is a grammatical role, not necessarily a person performing an action: The window broke.",
  ),
  s(
    "sentence-structure",
    "foundations",
    "phrases-and-heads",
    "Phrases, heads and dependents",
    "A phrase is organised around a head: a noun, verb, adjective, adverb or preposition. A phrase can contain only its head, or include modifiers and complements. Phrases can contain other phrases, so length alone does not distinguish a phrase from a clause. Find the central word and then identify the words that depend on it.",
    "the **roof** of the old house",
    [
      "The **roof** of the old house needs repair.",
      "She is **very proud of her team**.",
    ],
    "A noun phrase may contain a whole relative clause: the house that we bought. The larger phrase still has house as its head.",
  ),
  s(
    "sentence-structure",
    "foundations",
    "finite-subordinate-clauses",
    "Main, subordinate, finite and non-finite clauses",
    "A main clause can usually stand as a sentence. A subordinate clause functions inside another construction. A finite clause has a verb marked for tense or a modal; a non-finite clause uses an infinitive or participle without its own independent tense. Subordinate does not mean unimportant: it describes grammatical dependency.",
    "I know **that she left**. / I hope **to leave**.",
    [
      "**When the bell rang**, we left.",
      "They wanted **to finish before dark**.",
    ],
    "A short main clause such as Leave! is an imperative, so not every independent clause has an overt subject and tense-marked verb.",
  ),
  s(
    "sentence-structure",
    "foundations",
    "sentence-architectures",
    "Simple, compound and complex sentences",
    "A simple sentence contains one main clause. A compound sentence coordinates main clauses. A complex sentence contains subordination; a compound-complex sentence combines coordination and subordination. Count clauses, not verbs or words: a coordinated verb phrase can share one subject. The labels help you see how information is organised.",
    "one main clause · coordinated clauses · embedded clauses",
    [
      "Mina **opened the door and smiled**.",
      "Mina smiled **because we had arrived**, and Leo waved.",
    ],
    "Long does not automatically mean complex, and short does not automatically mean simple: I know you lied contains a subordinate content clause.",
  ),
  s(
    "sentence-structure",
    "clause-patterns",
    "clause-complements",
    "Subjects, objects and subject complements",
    "An object is selected by a verb; a subject complement describes or identifies the subject after a linking verb. Compare She met a doctor with She became a doctor. Linking verbs include be, seem, become and remain in relevant uses. A complement can be a noun phrase, adjective phrase or another licensed expression.",
    "subject + linking verb + **subject complement**",
    ["The room became **quiet**.", "My neighbour is **a doctor**."],
    "A noun after a verb is not automatically an object. A doctor identifies the subject after became; it is not something she acted on.",
  ),
  s(
    "sentence-structure",
    "clause-patterns",
    "transitivity-and-valency",
    "Transitive, intransitive and required complements",
    "Different verbs license different patterns, sometimes called valency. Arrive can form a clause without an object; put normally needs both an object and a location. Some verbs switch patterns: she opened the door / the door opened. A complement can be required even when it expresses a place or another circumstance.",
    "She **put** the keys **on the shelf**.",
    [
      "The children **laughed**.",
      "We **discussed the proposal**, but we **talked about it**.",
    ],
    "Do not infer the pattern from meaning alone: discuss something and talk about something express similar ideas but use different grammar.",
  ),
  s(
    "sentence-structure",
    "clause-patterns",
    "two-object-patterns",
    "Indirect objects, two objects and to/for phrases",
    "Some verbs allow a recipient followed by a thing: give someone something. Many also allow a thing followed by a to-phrase; some benefactive patterns use for. These alternatives depend on the verb and on the length and focus of each phrase. They cannot be applied to every verb of communication or transfer.",
    "give **her** a book / give a book **to her**",
    [
      "I sent **Sam a message**. / I sent a message **to Sam**.",
      "She made **us dinner**. / She made dinner **for us**.",
    ],
    "Explain and describe normally use to for the recipient: explain the problem to me, not explain me the problem.",
  ),
  s(
    "sentence-structure",
    "clause-patterns",
    "object-complements",
    "Object complements and resultative patterns",
    "An object complement describes or identifies the object. It can name a resulting state, as in paint the door blue, or a judgement, as in consider the plan sensible. Keep the object and its complement distinct: in elected her chair, her is the person and chair is the role.",
    "verb + object + **object complement**",
    ["The news made **everyone happy**.", "They elected **Nora chair**."],
    "An adjective can describe the resulting object while an adverb describes the action: she wiped the table clean / she wiped the table carefully.",
  ),
  s(
    "sentence-structure",
    "foundations",
    "grammar-meaning-context",
    "Grammatical form, meaning and context",
    "Grammar organises possible expressions, but context helps determine their intended meaning. A grammatical sentence can be unlikely or ambiguous. A request can have question form, and a past verb form can express politeness or unreality rather than past time. Separate how a sentence is built from what someone uses it to do.",
    "**form** + **context** → intended meaning",
    [
      "Could you move your bag? is normally a **request**.",
      "I was wondering whether you could help is a **polite current enquiry**.",
    ],
    "Unusual wording is not automatically ungrammatical. Judge the specified situation, register and variety rather than treating one preferred expression as the only possible one.",
  ),
  s(
    "question-forms",
    "sentence-types",
    "question-word-range",
    "What, which, whose, who and how",
    "Who asks about a person; whose asks about possession. What often asks for open information, while which usually selects from an understood set. How forms phrases about manner, degree, age, frequency and quantity. A question phrase may contain a noun or modifier and move as a unit.",
    "**Which train** / **How often** / **Whose coat**",
    [
      "**Which of these routes** is quickest?",
      "**How long** have you lived here?",
    ],
    "What and which overlap when the context supplies alternatives. Do not choose between them using a rigid noun-only rule.",
  ),
  s(
    "question-forms",
    "sentence-types",
    "negative-and-alternative-questions",
    "Negative questions, alternatives and replies",
    "Negative questions can express surprise, confirmation or an invitation. Alternative questions ask the listener to choose, rather than simply answer yes or no. In standard English, yes normally confirms a positive proposition and no confirms a negative one; repeating the verb removes uncertainty in replies to negative questions.",
    "Didn’t you go? — **Yes, I did. / No, I didn’t.**",
    [
      "Would you prefer **tea or coffee**?",
      "**Isn’t she coming?** — No, she isn’t.",
    ],
    "The tone and context of a negative question matter: Wouldn’t you like a seat? can be an offer, not an accusation.",
  ),
  s(
    "question-forms",
    "sentence-types",
    "echo-rhetorical-questions",
    "Echo, checking and rhetorical questions",
    "An echo question repeats or queries information just heard and may keep statement word order. A checking question asks for confirmation. A rhetorical question has question form but often makes a point instead of seeking new information. These uses depend strongly on conversation and intonation.",
    "You paid **how much**?",
    ["You’re leaving **today**?", "Who could refuse an offer like that?"],
    "Statement word order in an echo question does not license the same order for every neutral information question: Where do you live? is the ordinary direct form.",
  ),
  s(
    "imperatives",
    "sentence-types",
    "exclamative-clauses",
    "Exclamations with what and how",
    "Exclamatives often begin with what or how and express a strong evaluation. What introduces a noun phrase; how introduces an adjective or adverb phrase. Their order differs from ordinary questions. An exclamation mark can also turn many other sentence forms into emphatic writing, so punctuation alone does not identify an exclamative construction.",
    "**What a** lovely day! / **How** quickly she ran!",
    ["**What useful advice** that was!", "**How patient you are**!"],
    "Use a/an with a singular count noun after what; omit it with plural or uncountable nouns: What beautiful flowers! What luck!",
  ),
  s(
    "imperatives",
    "sentence-types",
    "imperative-subjects-and-let",
    "Imperatives with subjects, do and let",
    "Although the subject you is often omitted, an imperative can have an explicit subject for contrast or allocation: You wait here; somebody call a doctor. Do can emphasise an invitation or instruction. Let can introduce permission or a third-person proposal. Distinguish let them leave from the inclusive suggestion let’s leave.",
    "**Do sit down. / Nobody move.**",
    [
      "**You take the front**, and I’ll take the back.",
      "**Let the others finish** before we begin.",
    ],
    "Please and do affect tone but do not make every imperative polite in every relationship. Let’s and lets remain different forms.",
  ),
  s(
    "linking-clauses",
    "coordination",
    "coordination-and-parallelism",
    "Coordinating words, phrases and clauses",
    "And, or and but can join units at different levels: words, phrases or clauses. Coordinated units normally perform compatible grammatical jobs. Parallel wording makes a list easier to interpret, especially when units share an opening verb or preposition. The relationship may be addition, an alternative or a contrast.",
    "reading **and** writing · on Monday **or** on Tuesday",
    [
      "The room was **small but comfortable**.",
      "She wants **to study, to travel and to work abroad**.",
    ],
    "A conjunction does not repair an incompatible shared pattern: interested in music and to paint should be rephrased as interested in music and painting.",
  ),
  s(
    "linking-clauses",
    "coordination",
    "correlative-coordination",
    "Both…and, either…or, neither…nor",
    "Paired coordinators mark how two alternatives or parts belong together. Place the paired words before corresponding grammatical units. With neither…nor, the coordination already has negative meaning. Agreement with alternatives of different persons or numbers can sound awkward; a plural reformulation often gives the clearest result.",
    "**both** the book **and** the film",
    [
      "You can **either stay here or come with us**.",
      "She is **not only a musician but also a teacher**.",
    ],
    "Not only at the beginning of a clause can trigger inversion: Not only did she sing, but she also played. In the middle of a noun phrase, it does not.",
  ),
  s(
    "linking-clauses",
    "coordination",
    "shared-material-coordination",
    "Sharing and omitting repeated material",
    "Coordinated phrases and clauses can share grammatical material when the missing part is recoverable. The scope of a shared modifier can be ambiguous, so repeat it when necessary. In formal writing, make it clear whether a description applies to both parts or only the nearest one.",
    "Leo ordered tea and Mia **[ordered]** coffee.",
    [
      "She **opened and read** the letter.",
      "We invited **the teachers and the students**.",
    ],
    "Old men and women can describe two groups in different ways. If age applies to both, write old men and old women when clarity matters.",
  ),
  s(
    "noun-modifiers",
    "coordination",
    "apposition-and-supplements",
    "Apposition, parenthetical additions and supplements",
    "Apposition places two expressions referring to the same thing together. An integrated description identifies the referent; a supplementary description adds information about an already identified referent. Commas, dashes or parentheses can mark an added comment. The choice changes how essential the information appears.",
    "My sister **Leila** / Leila, **my sister**",
    [
      "Our guide, **an experienced climber**, led the way.",
      "The writer **Toni Morrison** won the prize.",
    ],
    "Do not automatically place commas around every name. The context determines whether the name identifies which person or merely adds information.",
  ),
  s(
    "contrast-concession",
    "adjuncts",
    "conditional-alternatives",
    "Unless, provided that, as long as and in case",
    "Unless introduces an exception, often paraphrasable with if not. Provided that and as long as set a condition. In case normally explains a precaution against a possible event; it is not simply another spelling of if. Keep the intended relationship clear before choosing the connector.",
    "Take a torch **in case** it gets dark.",
    [
      "You may borrow it **provided that you return it**.",
      "We will go **unless it rains**.",
    ],
    "I’ll take an umbrella in case it rains means taking it as a precaution. I’ll take one if it rains makes taking it dependent on the rain.",
  ),
  s(
    "contrast-concession",
    "adjuncts",
    "even-if-even-though",
    "Even if, even though and whether…or",
    "Even though presents a concession treated as a fact. Even if considers a condition and says the result will hold despite it. Whether…or can present alternative conditions with the same outcome. Do not select only from the presence of an unexpected result; decide whether the condition is asserted as true.",
    "**Even though** it rained / **Even if** it rains",
    [
      "We went out **even though it was cold**.",
      "We will finish **whether you help or not**.",
    ],
    "Even when often concerns an actual or recurring situation; even if often concerns a hypothetical one. Context can make the boundary less sharp.",
  ),
  s(
    "linking-clauses",
    "adjuncts",
    "adjunct-types-and-position",
    "Manner, means, accompaniment, viewpoint and stance",
    "Adjuncts can locate an event or describe how, by what means, with whom, from what viewpoint or with what attitude it is presented. Some attach closely to a verb phrase; others comment on the whole clause. Front position often frames the message, while end position commonly adds new circumstances.",
    "**By train**, **with a friend**, **in my opinion**",
    [
      "She solved it **by checking the figures**.",
      "**Fortunately**, nobody was hurt.",
    ],
    "An adverb after a linking verb may not do the job of a subject adjective: she looks happy describes her appearance; she looks happily at the photo describes her action.",
  ),
  s(
    "linking-clauses",
    "adjuncts",
    "time-clause-relations",
    "Before, after, until, by the time, once and whenever",
    "Time clauses locate one event relative to another. Until marks continuation to an endpoint; by the time identifies a reference point by which something is true or complete. Once marks a condition becoming satisfied; whenever marks any or every relevant occasion. Ordinary future time clauses normally use a present form.",
    "Wait **until** I arrive. / Finish **by the time** I arrive.",
    [
      "**Once you have paid**, we will send the ticket.",
      "She calls **whenever she needs advice**.",
    ],
    "Future reference does not require will inside every subordinate clause: I’ll call when I arrive. An embedded question is different: I don’t know when she will arrive.",
  ),
];
