import { section as s } from "./domains.mjs";
const word = ["cambridge-word-formation", "cambridge-comprehensive-scope"];
const spoken = ["cambridge-spoken", "cambridge-comprehensive-scope"];
export const sections = [
  s(
    "noun-modifiers",
    "word-formation",
    "inflection-versus-derivation",
    "Inflection versus derivation",
    "Inflection supplies grammatical forms of a word, such as books or walked. Derivation creates a related lexical item, sometimes changing its word class: teach → teacher. A word can contain both: teachers includes a derivational ending and a plural ending. Recognising the layers helps you infer meaning and choose a grammatical form.",
    "teach + **er** + **s**",
    [
      "kind → **kindness** creates a noun.",
      "kind → **kinder** creates a comparative form.",
    ],
    "A suffix does not have exactly the same effect on every base. Word formation has lexical restrictions, so plausible-looking forms are not automatically established words.",
    word,
  ),
  s(
    "noun-modifiers",
    "word-formation",
    "prefixes-and-suffixes",
    "Prefixes, suffixes and word families",
    "Prefixes commonly adjust meaning, while suffixes often indicate word class or a related meaning. Learn families such as decide, decision and decisive with their spelling and stress. Negative prefixes include un-, in-/im-/il-/ir-, dis- and non-, but their distribution is not freely interchangeable.",
    "**un**happy · care**ful** · care**less**",
    [
      "possible → **impossible**; legal → **illegal**.",
      "develop → **development**; active → **activity**.",
    ],
    "Do not attach the same negative prefix to every adjective. Impossible, unhappy and dishonest are lexical patterns, not choices produced by one universal spelling rule.",
    word,
  ),
  s(
    "noun-modifiers",
    "word-formation",
    "conversion-compounding",
    "Conversion, compounds and the head of a compound",
    "Conversion uses an existing form as a new word class, such as email as a noun and verb. Compounding combines lexical units into a new expression. English compounds are often headed by the final element, but there are exceptions and idiomatic meanings. Spelling can be open, hyphenated or closed and may change over time.",
    "an **email** / to **email** · **toothbrush**",
    ["A **coffee cup** is a kind of cup.", "They **bottled** the juice."],
    "A compound’s meaning may not be predictable from its parts. A greenhouse is a particular structure, not simply any house painted green.",
    word,
  ),
  s(
    "noun-modifiers",
    "word-formation",
    "clipping-blending-abbreviations",
    "Clipping, blending, acronyms and back-formation",
    "Words can arise through shortening, combining portions of words, initials or reanalysis of an apparent ending. These processes explain vocabulary patterns without guaranteeing that every possible new formation is accepted. Acronyms are pronounced as words; initialisms are pronounced letter by letter. Formal writing may need the full expression on first use.",
    "advertisement → **ad** · breakfast + lunch → **brunch**",
    [
      "**UN** is pronounced letter by letter.",
      "**edit** was formed historically from editor.",
    ],
    "Word formation is not a substitute for checking an unfamiliar word’s actual use. A recognisable pattern can create a playful one-off expression rather than a standard dictionary item.",
    word,
  ),
  s(
    "noun-modifiers",
    "word-formation",
    "nominalisation-and-complements",
    "Nominalisation, agents and dense noun phrases",
    "Nominalisation presents an action or quality as a noun. It can help connect ideas across a text, but it can also hide who acts and make sentences dense. Related verbs and nouns take different complement patterns. An of-phrase can be ambiguous between an agent and an affected participant, so use by or a full clause when needed.",
    "They investigated it → **their investigation of it**",
    [
      "**The committee’s rejection of the plan** caused a delay.",
      "**The destruction of the files by the fire** was complete.",
    ],
    "Nominalisation is not automatically more formal or better. Compare the clarity of We decided to leave with A decision regarding departure was made.",
    word,
  ),
  s(
    "noun-modifiers",
    "word-formation",
    "noun-modifier-number",
    "Nouns as modifiers and compound measurements",
    "A noun before another noun commonly classifies it and often has singular form: shoe shop. Some established modifiers are plural, such as sports centre and clothes shop. A measurement compound before a noun normally keeps its unit singular and is often hyphenated. After the noun, the ordinary plural measurement returns.",
    "a **five-minute** break / the break lasted **five minutes**",
    [
      "A **ten-year-old** child needs a ticket.",
      "We visited **a sports centre**.",
    ],
    "The common singular-modifier pattern has lexical exceptions. Do not mechanically change every plural noun modifier to singular.",
    word,
  ),
  s(
    "agreement-advanced",
    "clause-patterns",
    "notional-proximity-agreement",
    "Grammatical, notional and proximity agreement",
    "Agreement usually follows the grammatical head, but meaning and nearby alternatives also influence established patterns. A collective noun can be singular as a unit or plural as members, especially in British English. A sum or measurement can be treated as one amount. Rephrase mixed-number alternatives when agreement becomes distracting.",
    "**Ten pounds is** enough.",
    [
      "**The team is** winning. / **The team are** arguing among themselves.",
      "**A number of people are** waiting; **the number is** increasing.",
    ],
    "A plural noun inside an of-phrase does not normally control agreement with a singular head: the quality of the reports is high.",
  ),
  s(
    "agreement-advanced",
    "clause-patterns",
    "agreement-special-subjects",
    "Subjects that are clauses, titles and coordinated ideas",
    "A clause used as a subject generally takes singular agreement. A title can denote one work even when its words look plural. Coordinated nouns normally take plural agreement, but a conventional pairing or one combined concept can be treated as singular. Meaning and established usage must be read alongside the visible word forms.",
    "**What she said was** helpful.",
    [
      "**Reading before bed helps** me relax.",
      "**Bread and butter is** all we have for breakfast.",
    ],
    "A fused relative with plural interpretation may allow plural agreement in some patterns: What we need are more chairs. Avoid reducing all what-clause agreement to one mechanical rule.",
  ),
  s(
    "punctuation-clauses",
    "punctuation",
    "sentence-boundaries-fragments",
    "Full stops, fragments and comma splices",
    "A full stop normally ends an independent written sentence. A comma alone does not ordinarily join two independent clauses in formal edited prose. A fragment lacks the structure expected of a full sentence, but fragments can be deliberate in dialogue, headings or literary writing. Choose punctuation for the construction and the intended register.",
    "We waited. **The bus never came.**",
    [
      "We waited, **but** the bus never came.",
      "**Because it was late**, we left.",
    ],
    "Because it was late is a dependent clause, not normally a standalone formal sentence. Its use as a conversational answer is a different context.",
  ),
  s(
    "punctuation-clauses",
    "punctuation",
    "commas-and-clause-relations",
    "Commas with clauses, lists and supplementary information",
    "Commas separate items, frame introductory material and set off supplements. They normally do not divide a subject from its predicate or a verb from its ordinary object. Relative-clause commas can change whether information identifies a referent or merely adds a comment. A serial comma is a house-style choice unless clarity requires restructuring.",
    "My neighbour, **who works nights**, is asleep.",
    [
      "After the meeting, **we went home**.",
      "We invited **teachers, parents and students**.",
    ],
    "A pause in speech does not automatically require a comma. Grammar and intended grouping are more reliable than placing punctuation wherever you breathe.",
  ),
  s(
    "punctuation-clauses",
    "punctuation",
    "colons-semicolons-dashes",
    "Colons, semicolons and dashes",
    "A colon commonly introduces an explanation, expansion or list after a complete introductory clause. A semicolon links related independent clauses or separates complex list items. A dash can mark an interruption or added explanation more emphatically. Each mark signals a relationship; none is simply a decorative substitute for a comma.",
    "One problem remained: **the key was missing**.",
    [
      "The road was closed; **we took a detour**.",
      "There was one answer—**leave immediately**.",
    ],
    "Do not routinely insert a colon between a verb and its direct object: We bought apples and pears needs no colon after bought.",
  ),
  s(
    "punctuation-clauses",
    "punctuation",
    "quotation-and-dialogue",
    "Quotation marks, reporting clauses and quoted punctuation",
    "Quotation marks distinguish exact wording from the surrounding report. A reporting clause can precede, interrupt or follow dialogue. Use capitals and sentence punctuation according to the quoted unit. British and American house styles differ in quotation marks and punctuation placement, especially when the punctuation is not part of the original quotation.",
    "She said, **“We are ready.”**",
    [
      "**“Are you ready?”** she asked.",
      "He called the result **“unexpected”**.",
    ],
    "Do not convert a partial quotation into a full sentence merely because it is inside quotation marks. Match the punctuation to what is actually quoted.",
  ),
  s(
    "punctuation-clauses",
    "punctuation",
    "apostrophes-hyphens-brackets",
    "Apostrophes, hyphens, parentheses and ellipsis marks",
    "Apostrophes commonly mark possession or omitted letters, not ordinary plurals. Hyphens can clarify compound modifiers; parentheses enclose secondary information. An ellipsis mark can indicate omitted quoted material or a trailing utterance, but must not distort the source. These conventions work alongside the grammatical structure.",
    "a **well-known** writer · **its** cover / **it’s** open",
    [
      "The editor **(who had just arrived)** checked the text.",
      "The report concerns **twenty-year-old buildings**.",
    ],
    "A compound modifier ending in a normal -ly adverb usually needs no hyphen: a carefully written letter. Hyphenation of established compounds can be dictionary- or house-style-specific.",
  ),
  s(
    "punctuation-clauses",
    "punctuation",
    "capitals-numerals-abbreviations",
    "Capitalisation, numbers, abbreviations and typography",
    "Capitalise sentence openings, the pronoun I and proper names, including languages and days. Generic nouns usually stay lower-case unless they form part of a name or title under the chosen style. Numerals, dates, abbreviated titles and headings have conventions that vary by purpose and region. Consistency makes a document easier to interpret.",
    "**Monday**, **English**, **I** · the **university**",
    ["She studies **French history**.", "We met **Dr Patel** at the clinic."],
    "Capitalisation does not reliably identify a grammatical category: a common noun can begin a sentence, and brand names may use unconventional case.",
  ),
  s(
    "register-variation",
    "usage",
    "hedging-and-stance",
    "Hedging: expressing uncertainty and softening a claim",
    "Hedging adjusts the strength or directness of a statement through modals, stance verbs, adverbs and approximating expressions. It can reflect genuine uncertainty or interpersonal care. Choose wording proportional to the evidence rather than making every sentence vague. Stronger expressions can signal greater commitment when it is justified.",
    "It **seems that**… / This **may suggest**…",
    [
      "The change **appears to have helped**.",
      "I’m **not entirely sure** that this is the best option.",
    ],
    "Might and seems do not make an unsupported claim reliable. Hedging changes the speaker’s commitment; it does not supply evidence.",
    ["cambridge-hedges", "cambridge-comprehensive-scope"],
  ),
  s(
    "register-variation",
    "usage",
    "spoken-headers-tails",
    "Headers and tails in spoken English",
    "Conversation can introduce a topic before the main clause and then refer to it with a pronoun; this is a header. A tail names or clarifies a referent after the clause. These patterns help listeners process a message in real time. They are especially associated with speech and informal contexts rather than neutral edited exposition.",
    "**That new café**, it’s always busy.",
    [
      "She’s very patient, **your sister**.",
      "**The train we caught**, it stopped at every station.",
    ],
    "A spoken header is a licensed discourse pattern, not a model for every formal sentence. In formal writing, The new café is always busy is often more suitable.",
    ["cambridge-headers-tails", "cambridge-spoken"],
  ),
  s(
    "register-variation",
    "usage",
    "discourse-markers-response-tokens",
    "Discourse markers, response tokens and interjections",
    "Words such as well, so, anyway and right help organise turns, transitions and responses. Oh, ah and similar interjections can mark a reaction or a change of understanding. Their conversational job may be separate from the propositional content. Some linking expressions suit formal writing; others mainly suit speech.",
    "**Well**, I’m not sure. / **Anyway**, let’s continue.",
    [
      "**Oh**, I thought the meeting was tomorrow.",
      "**Right**, shall we begin?",
    ],
    "So can link a result, introduce a new topic or request continuation. Identify its function in the actual exchange rather than assigning one meaning to every occurrence.",
    spoken,
  ),
  s(
    "ellipsis-substitution",
    "usage",
    "spoken-ellipsis",
    "Conversational ellipsis and recoverable subjects",
    "Speech often omits material recoverable from the situation: Want a coffee? for Do you want a coffee? Short replies omit repeated predicates. Context makes these expressions understandable. Formal standalone writing usually needs more explicit structure, while dialogue, messages and headings can use appropriate reductions.",
    "**Seen Maya?** / **Sounds good.**",
    [
      "A: Who wants tea? B: **I do**.",
      "A: When are you leaving? B: **Tomorrow**.",
    ],
    "Omission is constrained by grammar and recoverability. It is not permission to delete arbitrary words from a sentence or leave a formal argument without a clear subject.",
    spoken,
  ),
  s(
    "question-tags",
    "usage",
    "tags-intonation-and-response",
    "Question-tag intonation, checking and social meaning",
    "A tag can ask for genuine confirmation, invite agreement or manage the tone of a remark. Rising or falling intonation often helps distinguish these purposes, but context also matters. Some tags are conventional exceptions to the basic polarity pattern, and invariant tags such as right? occur in informal conversation.",
    "You’re coming, **aren’t you**?",
    ["I’m late, **aren’t I**?", "Close the door, **will you**?"],
    "A tag is not always a neutral request for information. Depending on tone, the same words can sound friendly, insistent, surprised or critical.",
    spoken,
  ),
  s(
    "register-variation",
    "usage",
    "politeness-distance-indirectness",
    "Politeness, grammatical distance and indirect requests",
    "Past forms and modal constructions can create interpersonal distance without referring to past time. Indirect questions and conditional wording can soften requests, while concise imperatives can be appropriate in instructions. Politeness depends on relationship, situation and tone as well as grammatical form. More words do not automatically make a request more considerate.",
    "I **was wondering** if you could help.",
    [
      "**Would you mind opening** the window?",
      "**Could I ask you to wait** a moment?",
    ],
    "Would you mind…? conventionally takes an -ing clause; a reply such as Not at all normally accepts the request. Consider the meaning before interpreting yes or no.",
    spoken,
  ),
  s(
    "register-variation",
    "usage",
    "regional-standard-variation",
    "British, American and other standard varieties",
    "Standard English is shared across communities but includes regional preferences in tense, agreement, prepositions and certain constructions. British English often uses present perfect with just or already where American English also uses past simple. Collective agreement and institutional articles show further variation. Label the intended variety when a question depends on it.",
    "BrE **in hospital** / AmE **in the hospital**",
    [
      "BrE often: **Have you eaten yet?** / AmE also: **Did you eat yet?**",
      "BrE **at the weekend** / AmE **on the weekend**.",
    ],
    "These are tendencies, not a rule that every British or American speaker makes the same choice. Regional varieties beyond these two also have established standard conventions.",
    spoken,
  ),
  s(
    "register-variation",
    "usage",
    "formal-informal-and-genres",
    "Formal writing, informal language and genre",
    "Grammar choices respond to audience and purpose. Academic and official writing often make reference and logical relationships explicit; conversation can depend on shared context. Headlines, instructions, notes and literary narration have their own conventional reductions and patterns. A form appropriate in one genre may be distracting in another without being universally wrong.",
    "**No entry** in a sign / **Visitors must not enter** in a rule",
    [
      "A headline may say **Mayor opens new library**.",
      "An instruction may begin **Add the flour**.",
    ],
    "Do not equate every informal construction with an error or every passive with good formal style. Choose the structure that expresses the intended relationship clearly.",
    spoken,
  ),
  s(
    "register-variation",
    "usage",
    "grammar-conventions-and-change",
    "Rules, preferences, variation and language change",
    "Some constraints define a standard construction; others are strong preferences or editorial conventions. English changes and permits more variation than a short rule often suggests. Dictionaries and reference grammars help resolve lexical and regional questions. A useful learner grammar explains both the stable pattern and the contexts in which alternatives occur.",
    "a **construction rule** / a **style preference**",
    [
      "**Who are you talking to?** is standard despite its final preposition.",
      "**To clearly explain** can be appropriate; split infinitives are not universally ungrammatical.",
    ],
    "A grammar map describes systems and productive patterns. It cannot list every possible sentence, every lexical idiom or all historical and regional constructions as a finite exercise bank.",
    spoken,
  ),
];
