import { section as s } from "./domains.mjs";
export const sections = [
  s(
    "present-simple-be",
    "verbs",
    "auxiliary-and-lexical-verbs",
    "Main verbs, auxiliaries and the first auxiliary",
    "Be, have and do can act as main verbs or auxiliaries. Auxiliaries build questions, negatives, aspect, voice and emphasis. In a chain, the first auxiliary carries tense and agreement and moves in a question. Later verbs take the form required by the preceding auxiliary. A lexical verb may need do-support when no other auxiliary is available.",
    "**Has** she **been working**?",
    [
      "They **have** a car. / They **have finished**.",
      "He **does** the shopping. / **Does** he shop here?",
    ],
    "Possessive have uses different question patterns across varieties: Do you have…? is widely used; Have you got…? is especially common in British conversation.",
  ),
  s(
    "present-simple",
    "verbs",
    "tense-aspect-time",
    "Tense, aspect and time are different dimensions",
    "Tense is a grammatical form; time is when a situation is located; aspect is how the speaker views its course. English present and past forms combine with perfect and progressive constructions. Future meaning uses several constructions. A familiar classroom tense name is useful shorthand, but it does not determine meaning independently of context.",
    "**past form** ≠ always **past time**",
    [
      "The train **leaves tomorrow**.",
      "If I **knew** the answer now, I would tell you.",
    ],
    "Calling will a future tense is a common teaching convention. It does not mean every future event must use will or every use of will concerns future time.",
  ),
  s(
    "present-continuous",
    "verbs",
    "progressive-viewpoint",
    "Progressive aspect: activity, temporary situation and repeated irritation",
    "The progressive views a situation as unfolding around a reference point; it need not be happening at the exact instant of speaking. It can present a temporary arrangement or a repeated behaviour viewed emotionally, especially with always. Choosing simple or progressive changes viewpoint, not merely the length of an activity.",
    "She **works** here. / She **is working** here this month.",
    [
      "I’m **reading** a long novel at the moment.",
      "You’re **always leaving** the lights on!",
    ],
    "A short event can be progressive if it is viewed in progress, while a long-lasting state can be simple. Duration alone does not select the form.",
  ),
  s(
    "present-perfect",
    "verbs",
    "perfect-versus-past",
    "Present perfect versus a finished past",
    "Use present perfect when an earlier situation is connected to a present reference frame, such as experience so far, an unfinished period or a current result. Past simple places it in a finished past frame. Speakers can choose a frame rather than simply obey a keyword. British and American usage differs with some recent-event expressions.",
    "I **have seen** it. / I **saw** it yesterday.",
    [
      "I **have had** two coffees today, and the day is not over.",
      "When I lived there, I **visited** the museum twice.",
    ],
    "A present consequence does not forbid past simple: I lost my key yesterday is correct even if it is still missing. The explicit finished time selects the past frame.",
  ),
  s(
    "present-perfect",
    "verbs",
    "perfect-adverbs-duration",
    "For, since, ever, never, just, already, yet and still",
    "For measures a duration; since gives its starting point. Ever and never relate an event to a period of possible experience. Just, already, yet and still locate it relative to expectation or continuation. Their positions and tense preferences depend on meaning and variety. They are clues, not automatic tense selectors.",
    "**for three years** / **since 2022**",
    [
      "She has **already left**, but he has **not left yet**.",
      "I lived there **for three years** before moving away.",
    ],
    "Since can also mean because, and for can express a purpose or recipient. Identify the word’s function before using it to reason about tense.",
  ),
  s(
    "present-perfect",
    "verbs",
    "been-gone-and-continuing-states",
    "Been, gone, finished events and continuing states",
    "Have been to commonly presents a visit as completed, while have gone to commonly indicates departure with the person still away. Perfect simple with a state can describe something continuing now. A negative perfect can also measure a period with no occurrence. Interpret the reference time and lexical meaning together.",
    "She has **been to** Rome. / She has **gone to** Rome.",
    [
      "I have **known** him for years.",
      "We **haven’t heard** from her since Monday.",
    ],
    "Have been in a place for a duration may mean the person is still there. The completed-visit reading of been to should not be imposed on every construction with been.",
  ),
  s(
    "past-perfect",
    "verbs",
    "narrative-time-frames",
    "Narrative sequencing and optional past perfect",
    "Past perfect locates a situation before a past reference point, especially when the story moves backwards. Past simple can continue a sequence once the order is established. Before and after can make the order clear without past perfect. Narrative present is another stylistic way to tell events, provided the perspective remains coherent.",
    "She arrived, but he **had left**.",
    [
      "After she **finished**, she went home.",
      "He opened the box. Inside, someone **had hidden** a note.",
    ],
    "Do not keep every earlier event in past perfect throughout an entire story. Once the earlier time frame is established, past simple often carries the narrative.",
  ),
  s(
    "future-forms",
    "verbs",
    "future-in-the-past",
    "Future in the past: would and was going to",
    "A future viewed from a past point often uses would or was/were going to. The event may or may not later happen; context tells you whether the plan was fulfilled. Was about to can describe an imminent past event. Distinguish predictive would from conditional, habitual and polite uses of the same modal.",
    "She said she **would call**.",
    [
      "We **were going to leave**, but the car would not start.",
      "I **was about to speak** when the phone rang.",
    ],
    "Was going to does not itself guarantee cancellation: We were going to meet at six, and we did is possible.",
  ),
  s(
    "future-forms",
    "verbs",
    "future-periphrases",
    "Be about to, be due to, be to and likely to",
    "Future-oriented expressions add meanings beyond time. Be about to signals imminence; be due to refers to an expectation or schedule. Be to can express an official arrangement or instruction. Be likely to expresses probability. Choose the construction that matches the event’s status and the speaker’s stance.",
    "The train **is due to arrive** at six.",
    [
      "The film **is about to begin**.",
      "Visitors **are to remain** behind the barrier.",
    ],
    "Be about to normally describes the immediate future, so it is unsuitable for a distant plan without a shifted viewpoint. Due to + noun can instead mean because of.",
  ),
  s(
    "stative-dynamic",
    "verbs",
    "lexical-aspect-and-states",
    "States, activities, accomplishments and punctual events",
    "Verbs and their complements describe different event types: a state, an ongoing activity, an activity with an endpoint or a brief change. This affects progressive and perfect interpretations. A verb can change its event type with a different sense or object. The categories help explain patterns but do not replace contextual judgement.",
    "**run** / **run a kilometre**",
    [
      "She **was finding** new errors every day.",
      "He **has been building** a house, but he **has built** the wall.",
    ],
    "Do not ban every progressive use of a usually stative verb. I’m thinking about it uses a different sense from I think it is correct.",
  ),
  s(
    "past-habits",
    "verbs",
    "habit-state-would-used",
    "Used to, would and past simple: meaning choices",
    "Used to can present a past state or habit that contrasts with the present. Habitual would normally needs an established past setting and describes repeated events. Past simple can express either without explicitly foregrounding the contrast with now. Choosing a form changes the presentation, even when all describe the same past period.",
    "We **used to live** nearby. / We **would walk** there daily.",
    [
      "As children, we **would build** shelters in the woods.",
      "I **used to own** a motorbike.",
    ],
    "Would can describe a characteristic state in some special contexts, but ordinary past possession is better introduced with used to or past simple.",
  ),
  s(
    "modal-obligation",
    "verbs",
    "modal-meanings-and-semi-modals",
    "Modal meanings and semi-modal expressions",
    "Modals express judgements, possibilities, requirements, willingness and interpersonal meanings. The same form can have several uses. Expressions such as have to, be able to, be allowed to and be supposed to supply forms or meanings that central modals lack. Their question and negative grammar differs from that of can or must.",
    "**must leave** / **had to leave**",
    [
      "You **are supposed to sign** here.",
      "Will you help? can ask about **willingness**, not only future time.",
    ],
    "Central modals do not normally combine directly: will can is not standard. Use an appropriate expression such as will be able to.",
  ),
  s(
    "modal-obligation",
    "verbs",
    "ought-need-dare-had-better",
    "Ought to, need, dare, had better and would rather",
    "Ought usually takes to; had better takes the bare infinitive and often carries a warning about consequences. Need and dare can behave as ordinary verbs or, in some uses and varieties, as modal-like auxiliaries. Would rather expresses preference. Learn their construction patterns as well as their broad meanings.",
    "You **had better leave**. / You **ought to leave**.",
    [
      "You **need not wait**. / You **do not need to wait**.",
      "I **would rather stay** than leave.",
    ],
    "Had better concerns a present or future recommendation despite had. Its ordinary negative is had better not; it is not a statement about the past.",
  ),
  s(
    "modal-deduction",
    "verbs",
    "modal-ambiguity-and-strength",
    "Possibility, deduction, permission and ability",
    "Can, could, may and might do different jobs in different contexts. A general possibility differs from a tentative judgement about one situation. Must can express an obligation or a strong inference. Should can express advice or an expectation. Identify whether the speaker is reasoning about reality or regulating an action.",
    "You **must be tired** / You **must wear a helmet**",
    ["It **can be cold** here in spring.", "She **may be at home** now."],
    "Do not assign fixed numerical probabilities to may, might or could. Their strength depends on context, stress and the alternatives under discussion.",
  ),
  s(
    "past-modals",
    "verbs",
    "could-have-didnt-need",
    "Could have, might have and didn’t need to",
    "Modal + have + participle can express a judgement about the past, an unrealised opportunity or criticism. Could have does not always mean the event failed to happen; it can mean that it possibly happened. Needn’t have normally presents an action as done but unnecessary. Didn’t need to states absence of necessity and needs context to establish whether it happened.",
    "You **needn’t have bought** it.",
    [
      "She **could have missed** the train; I’m not sure.",
      "We **didn’t need to book**, but we booked anyway.",
    ],
    "Do not assume every could have sentence is counterfactual. Contrast We could have won, but we lost with That noise could have been the wind.",
  ),
  s(
    "unreal-subjunctive",
    "verbs",
    "indicative-imperative-subjunctive",
    "Mood: statements, directives and subjunctive patterns",
    "Mood concerns how a clause presents a proposition or directive. Ordinary indicative forms occur in statements and many questions. Imperatives give directives. The plain-form subjunctive appears after some demands, recommendations and formulaic expressions. Irrealis were marks remote hypothetical meaning. Terminology varies between teaching and descriptive grammars, so learn the construction as well as the label.",
    "They insist that he **be** present.",
    [
      "It is essential that she **not be** disturbed.",
      "If I **were** in your position, I would ask.",
    ],
    "British English also often uses should in mandative clauses: They insist that he should be present. This is a standard alternative, not an error.",
  ),
  s(
    "unreal-subjunctive",
    "verbs",
    "as-if-rather-and-formulae",
    "As if, would rather, it’s time and fixed subjunctives",
    "As if and as though compare an appearance with a situation; a past or past-perfect form can mark remoteness, while ordinary forms can leave the situation open. Would rather + a different subject often takes a past form for a present preference. Some subjunctives survive in fixed wishes or formal concessions.",
    "I’d rather **you stayed**.",
    [
      "He acts **as if he owned** the place.",
      "**Be that as it may**, we still need a decision.",
    ],
    "As if does not always require unreal past: It looks as if it is going to rain presents an apparently likely situation.",
  ),
  s(
    "present-simple",
    "inflection",
    "verb-form-paradigms",
    "The five main verb forms and irregular families",
    "Most lexical verbs have a base, an -s form, a past form, a past participle and an -ing form. Some share spellings; others differ. Be has additional person/number forms. The auxiliary construction tells you which form to use. A dictionary’s principal parts are the right reference for lexical irregularities.",
    "**write · writes · wrote · written · writing**",
    [
      "**cut · cuts · cut · cut · cutting**",
      "**go · goes · went · gone · going**",
    ],
    "Past and past participle are separate categories even when they look alike: I worked / I have worked; I went / I have gone.",
  ),
  s(
    "present-continuous",
    "inflection",
    "spelling-endings",
    "Spelling changes with -s, -ed and -ing",
    "Common spelling patterns include consonant + y changing before -s or -ed, final silent e dropping before -ing, and a final consonant doubling after a short stressed vowel in suitable patterns. Vowel + y normally keeps y. These are spelling rules tied to sound and stress, with lexical and regional exceptions.",
    "stud**ies** · stud**ied** · study**ing**",
    [
      "**stop → stopped → stopping**",
      "**make → making**, but **see → seeing**",
    ],
    "Do not double w, x or y by the ordinary doubling rule. Travelling/traveling reflects a standard British/American spelling difference.",
  ),
  s(
    "present-simple-be",
    "inflection",
    "contraction-ambiguity",
    "Contractions, strong forms and ambiguity",
    "A contraction reduces an auxiliary or negative in writing to reflect common spoken forms. ’s can mean is or has; ’d can mean had or would. Read the following verb to resolve the form. Positive contracted auxiliaries normally cannot stand alone at the end of a short answer where stress falls on them.",
    "She**’s** waiting / She**’s** finished",
    [
      "Yes, **I am**, not Yes, I’m.",
      "I **would have** helped. / I**’d have** helped.",
    ],
    "Could’ve is a contraction of could have, not could of. The sound resemblance does not change the auxiliary construction.",
  ),
];
